//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailySoccer.DAC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int RewardGroupId { get; set; }
        public int AccountId { get; set; }
        public Nullable<System.DateTime> ManualSelectedDate { get; set; }
        public Nullable<System.DateTime> RandomSelectedDate { get; set; }
    
        public virtual RewardGroup RewardGroup { get; set; }
        public virtual Account Account { get; set; }
    }
}
