// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DailySoccer.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class GetAllGuessHistoryFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GetAllGuessHistory.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "GetAllGuessHistory", "In order to avoid silly mistakes\r\nAs a math idiot\r\nI want to be told the sum of t" +
                    "wo numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "GetAllGuessHistory")))
            {
                DailySoccer.Specs.GetAllGuessHistoryFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line 8
 testRunner.Given("Setup mocking", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "SecrectCode",
                        "Points",
                        "MaximumGuessAmount",
                        "CurrentOrderedCoupon"});
            table1.AddRow(new string[] {
                        "1",
                        "s01",
                        "0",
                        "5",
                        "0"});
#line 9
 testRunner.And("ผู้ใช้ในระบบมีดังนี้", ((string)(null)), table1, "And ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ผู้ใช้ที่ไม่เคยทายผลขอข้อมูลการทายผลทั้งหมด (ไม่มีข้อมูลแมช์) ระบบส่งรายการทายผลเ" +
            "ปล่ากลับไป")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GetAllGuessHistory")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mock")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mock")]
        public virtual void ผใชทไมเคยทายผลขอขอมลการทายผลทงหมดไมมขอมลแมชระบบสงรายการทายผลเปลากลบไป()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ผู้ใช้ที่ไม่เคยทายผลขอข้อมูลการทายผลทั้งหมด (ไม่มีข้อมูลแมช์) ระบบส่งรายการทายผลเ" +
                    "ปล่ากลับไป", new string[] {
                        "mock",
                        "mock"});
#line 14
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "LeagueName",
                        "BeginDate",
                        "StartedDate",
                        "CompletedDate"});
#line 15
 testRunner.Given("ในระบบมีข้อมูลแมช์เป็น", ((string)(null)), table2, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "AccountSecrectCode",
                        "MatchId",
                        "GuessTeamId"});
#line 17
 testRunner.And("ในระบบมีข้อมูลการทายเป็น", ((string)(null)), table3, "And ");
#line 19
 testRunner.When("ผู้ใช้ UserId: \'s01\' ขอข้อมูลการทายผลทั้งหมด", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Month",
                        "TotalPoints"});
#line 20
 testRunner.Then("ระบบส่งรายการทายผลกลับไปเป็น", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ผู้ใช้ที่ไม่เคยทายผลขอข้อมูลการทายผลทั้งหมด (มีข้อมูลแมช์) ระบบส่งรายการทายผลเปล่" +
            "ากลับไป")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GetAllGuessHistory")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mock")]
        public virtual void ผใชทไมเคยทายผลขอขอมลการทายผลทงหมดมขอมลแมชระบบสงรายการทายผลเปลากลบไป()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ผู้ใช้ที่ไม่เคยทายผลขอข้อมูลการทายผลทั้งหมด (มีข้อมูลแมช์) ระบบส่งรายการทายผลเปล่" +
                    "ากลับไป", new string[] {
                        "mock"});
#line 24
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "LeagueName",
                        "BeginDate",
                        "StartedDate",
                        "CompletedDate",
                        "TeamHome.Id",
                        "TeamHome.Name",
                        "TeamAway.Id",
                        "TeamAway.Name"});
            table5.AddRow(new string[] {
                        "1",
                        "Premier league",
                        "1/1/2015 01:00",
                        "1/1/2015 01:00",
                        "1/1/2015 02:30",
                        "1",
                        "Brentford",
                        "2",
                        "Hull City"});
            table5.AddRow(new string[] {
                        "2",
                        "Premier league",
                        "1/2/2015 01:00",
                        "1/2/2015 01:00",
                        "1/2/2015 02:30",
                        "3",
                        "Birmingham City",
                        "4",
                        "Blackburn Rovers"});
#line 25
 testRunner.Given("ในระบบมีข้อมูลแมช์เป็น", ((string)(null)), table5, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "AccountSecrectCode",
                        "MatchId",
                        "GuessTeamId"});
#line 29
 testRunner.And("ในระบบมีข้อมูลการทายเป็น", ((string)(null)), table6, "And ");
#line 31
 testRunner.When("ผู้ใช้ UserId: \'s01\' ขอข้อมูลการทายผลทั้งหมด", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Month",
                        "TotalPoints"});
#line 32
 testRunner.Then("ระบบส่งรายการทายผลกลับไปเป็น", ((string)(null)), table7, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
