// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DailySoccer.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class GuessMatchFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GuessMatch.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "GuessMatch", "In order to avoid silly mistakes\r\nAs a math idiot\r\nI want to be told the sum of t" +
                    "wo numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "GuessMatch")))
            {
                DailySoccer.Specs.GuessMatchFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line 8
 testRunner.Given("Setup mocking", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "LeagueName",
                        "BeginDate",
                        "StartedDate",
                        "CompletedDate",
                        "TeamHome.Id",
                        "TeamHome.Name",
                        "TeamHome.CurrentPredictionPoints",
                        "TeamAway.Id",
                        "TeamAway.Name",
                        "TeamAway.CurrentPredictionPoints"});
            table1.AddRow(new string[] {
                        "1",
                        "Premier league",
                        "1/1/2015 01:00",
                        "",
                        "",
                        "1",
                        "Brentford",
                        "6",
                        "2",
                        "Hull City",
                        "7"});
            table1.AddRow(new string[] {
                        "2",
                        "Premier league",
                        "1/1/2015 01:30",
                        "",
                        "",
                        "3",
                        "Birmingham City",
                        "8",
                        "4",
                        "Blackburn Rovers",
                        "9"});
#line 9
 testRunner.And("ในระบบมีข้อมูลแมช์เป็น", ((string)(null)), table1, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "SecrectCode",
                        "Points",
                        "MaximumGuessAmount",
                        "CurrentOrderedCoupon"});
            table2.AddRow(new string[] {
                        "1",
                        "s01",
                        "0",
                        "5",
                        "0"});
#line 13
 testRunner.And("ผู้ใช้ในระบบมีดังนี้", ((string)(null)), table2, "And ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ทายผลว่าทีมเย่าชนะให้กับแมช์ที่ยังไม่แข่ง ระบบทำการบันทึกการทายผลไว้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GuessMatch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mock")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mock")]
        public virtual void ทายผลวาทมเยาชนะใหกบแมชทยงไมแขงระบบทำการบนทกการทายผลไว()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ทายผลว่าทีมเย่าชนะให้กับแมช์ที่ยังไม่แข่ง ระบบทำการบันทึกการทายผลไว้", new string[] {
                        "mock",
                        "mock"});
#line 18
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "AccountSecrectCode",
                        "MatchId",
                        "GuessTeamId",
                        "PredictionPoints"});
#line 19
 testRunner.Given("ในระบบมีข้อมูลการทายเป็น", ((string)(null)), table3, "Given ");
#line 21
 testRunner.When("ผู้ใช้ UserId: \'s01\' ทายผลแมช์ MatchId: \'1\' IsGuessTeamHome: \'true\' เวลาในขณะนั้น" +
                    "เป็น \'1/1/2015 04:00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
 testRunner.Then("ระบบทำการบันทึกการทายผลไว้ UserId: \'s01\', MatchId: \'1\', GuessTeamId \'1\', Predicti" +
                    "onPoints \'6\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
