// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DailySoccer.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class RequestConfirmPhoneNumberFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "RequestConfirmPhoneNumber.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "RequestConfirmPhoneNumber", "In order to avoid silly mistakes\nAs a math idiot\nI want to be told the sum of two" +
                    " numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "RequestConfirmPhoneNumber")))
            {
                DailySoccer.Specs.RequestConfirmPhoneNumberFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line 8
 testRunner.Given("Setup mocking", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "SecretCode",
                        "VerifyCode"});
            table1.AddRow(new string[] {
                        "1",
                        "s01",
                        ""});
            table1.AddRow(new string[] {
                        "2",
                        "s02",
                        "+66914185555"});
#line 9
 testRunner.And("ผู้ใช้ในระบบมีดังนี้", ((string)(null)), table1, "And ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ผู้ใช้ทำการขอยืนยันเบอร์โทรศัพท์ ระบบบันทึกเบอร์โทรแล้วส่งรหัสลับในการยืนยันกลับไ" +
            "ป")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "RequestConfirmPhoneNumber")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mock")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mock")]
        public virtual void ผใชทำการขอยนยนเบอรโทรศพทระบบบนทกเบอรโทรแลวสงรหสลบในการยนยนกลบไป()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ผู้ใช้ทำการขอยืนยันเบอร์โทรศัพท์ ระบบบันทึกเบอร์โทรแล้วส่งรหัสลับในการยืนยันกลับไ" +
                    "ป", new string[] {
                        "mock",
                        "mock"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 16
 testRunner.When("ผู้ใช้ UserId: \'s01\' ขอยืนยันเบอร์โทรศัพ \'+66914185500\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
 testRunner.Then("ระบบบันทึกเบอร์โทร \'+66914185500\' ของผู้ใช้ UserId: \'s01\' แล้วส่งรหัสลับในการยืนย" +
                    "ันกลับไป", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ผู้ใช้ทำการขอยืนยันเบอร์โทรศัพท์แต่เป็นเบอร์ที่ไม่ถูกต้อง (สั้นกว่า 6 หลัก) ระบบไ" +
            "ม่ทำการบันทึกเบอร์โทรและไม่ส่งรหัสลับกลับไป")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "RequestConfirmPhoneNumber")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mock")]
        public virtual void ผใชทำการขอยนยนเบอรโทรศพทแตเปนเบอรทไมถกตองสนกวา6หลกระบบไมทำการบนทกเบอรโทรและไมสงรหสลบกลบไป()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ผู้ใช้ทำการขอยืนยันเบอร์โทรศัพท์แต่เป็นเบอร์ที่ไม่ถูกต้อง (สั้นกว่า 6 หลัก) ระบบไ" +
                    "ม่ทำการบันทึกเบอร์โทรและไม่ส่งรหัสลับกลับไป", new string[] {
                        "mock"});
#line 20
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 21
 testRunner.When("ผู้ใช้ UserId: \'s01\' ขอยืนยันเบอร์โทรศัพ \'12345\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
 testRunner.Then("ระบบไม่ทำการบันทึกเบอร์โทรและไม่ส่งรหัสลับกลับไป", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ผู้ใช้ทำการขอยืนยันเบอร์โทรศัพท์แต่เป็นเบอร์ที่ไม่ถูกต้อง (ยาวกว่า 20 หลัก) ระบบไ" +
            "ม่ทำการบันทึกเบอร์โทรและไม่ส่งรหัสลับกลับไป")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "RequestConfirmPhoneNumber")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mock")]
        public virtual void ผใชทำการขอยนยนเบอรโทรศพทแตเปนเบอรทไมถกตองยาวกวา20หลกระบบไมทำการบนทกเบอรโทรและไมสงรหสลบกลบไป()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ผู้ใช้ทำการขอยืนยันเบอร์โทรศัพท์แต่เป็นเบอร์ที่ไม่ถูกต้อง (ยาวกว่า 20 หลัก) ระบบไ" +
                    "ม่ทำการบันทึกเบอร์โทรและไม่ส่งรหัสลับกลับไป", new string[] {
                        "mock"});
#line 25
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 26
 testRunner.When("ผู้ใช้ UserId: \'s01\' ขอยืนยันเบอร์โทรศัพ \'012345678901234567890\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 27
 testRunner.Then("ระบบไม่ทำการบันทึกเบอร์โทรและไม่ส่งรหัสลับกลับไป", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ผู้ใช้ที่เคยยืนยันเบอร์โทรเสร็จสมบูรณ์ไปแล้วขอทำการยืนยันเบอร์โทรอีกครั้ง ระบบไม่" +
            "ทำการบันทึกเบอร์โทรและไม่ส่งรหัสลับกลับไป")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "RequestConfirmPhoneNumber")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mock")]
        public virtual void ผใชทเคยยนยนเบอรโทรเสรจสมบรณไปแลวขอทำการยนยนเบอรโทรอกครงระบบไมทำการบนทกเบอรโทรและไมสงรหสลบกลบไป()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ผู้ใช้ที่เคยยืนยันเบอร์โทรเสร็จสมบูรณ์ไปแล้วขอทำการยืนยันเบอร์โทรอีกครั้ง ระบบไม่" +
                    "ทำการบันทึกเบอร์โทรและไม่ส่งรหัสลับกลับไป", new string[] {
                        "mock"});
#line 30
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 31
 testRunner.When("ผู้ใช้ UserId: \'s02\' ขอยืนยันเบอร์โทรศัพ \'+66914185500\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
 testRunner.Then("ระบบไม่ทำการบันทึกเบอร์โทรและไม่ส่งรหัสลับกลับไป", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ผู้ใช้ที่ไม่มีในระบบขอยืนยันเบอร์โทรศัพ ระบบไม่ทำการบันทึกเบอร์โทรและไม่ส่งรหัสลั" +
            "บกลับไป")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "RequestConfirmPhoneNumber")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mock")]
        public virtual void ผใชทไมมในระบบขอยนยนเบอรโทรศพระบบไมทำการบนทกเบอรโทรและไมสงรหสลบกลบไป()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ผู้ใช้ที่ไม่มีในระบบขอยืนยันเบอร์โทรศัพ ระบบไม่ทำการบันทึกเบอร์โทรและไม่ส่งรหัสลั" +
                    "บกลับไป", new string[] {
                        "mock"});
#line 35
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 36
 testRunner.When("ผู้ใช้ UserId: \'unknow\' ขอยืนยันเบอร์โทรศัพ \'+66914185500\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 37
 testRunner.Then("ระบบไม่ทำการบันทึกเบอร์โทรและไม่ส่งรหัสลับกลับไป", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
